import {supabase} from './supabase'

export type DocumentType='technical_data_product_specification'|'ppwr_supplier_technical_information_statement'
export type DocumentStatus='draft'|'approved'|'issued'|'superseded'
export type SupportArea='heavy_metals'|'pfas'|'recyclability'|'recycled_content'|'biobased'|'compostability'|'reuse'|'food_contact'|'general'|'printing'
export type EvidenceSupportStatus='supported'|'partially_supported'|'evidence_missing'|'not_applicable'
export type PfasSupportStatus='supported'|'evidence_missing'|'not_applicable'

export async function listDocuments(){const {data,error}=await supabase.from('document_records').select('document_id,owner_organization_id,request_id,product_id,product_version_id,document_type,document_language,status,version_no,ruleset_id,customer_name_snapshot,customer_country_snapshot,customer_reference_snapshot,approved_at,issued_at,created_at,updated_at').order('updated_at',{ascending:false});if(error)throw error;return data||[]}
export async function listDocumentRequestOptions(){const {data,error}=await supabase.from('documentation_requests').select('request_id,request_number,request_status,product_description,documentation_requested,preferred_document_language,linked_product_id').in('request_status',['approved','issued']).order('updated_at',{ascending:false});if(error)throw error;return data||[]}
export async function createDocumentDraft(requestId:string,documentType:DocumentType,language:'cs'|'en'){const {data,error}=await supabase.rpc('create_document_draft',{target_request_id:requestId,target_document_type:documentType,target_language:language});if(error)throw error;return data}
export async function getDocument(documentId:string){const {data,error}=await supabase.from('document_records').select('document_id,owner_organization_id,request_id,product_id,product_version_id,document_type,document_language,status,version_no,ruleset_id,customer_name_snapshot,customer_country_snapshot,customer_reference_snapshot,approved_at,issued_at,created_at,updated_at').eq('document_id',documentId).single();if(error)throw error;return data}
export async function getDocument1Data(documentId:string){const {data,error}=await supabase.from('document1_technical_data').select('*').eq('document_id',documentId).maybeSingle();if(error)throw error;return data}
export async function getPpwrData(documentId:string){const {data,error}=await supabase.from('ppwr_statement_data').select('*').eq('document_id',documentId).maybeSingle();if(error)throw error;return data}
export async function savePpwrDraft(documentId:string,patch:Record<string,unknown>){const {data,error}=await supabase.rpc('save_ppwr_statement_draft',{target_document_id:documentId,patch});if(error)throw error;return data}
export async function listDocumentEvidence(documentId:string){const {data,error}=await supabase.from('document_evidence_links').select('document_id,evidence_id,support_area,created_at,evidence_records(evidence_id,title,evidence_type,verification_status,valid_until,related_request_id,related_product_id,related_product_version_id,sha256)').eq('document_id',documentId).order('created_at');if(error)throw error;return data||[]}
export async function listEvidenceForVersion(productVersionId:string){const {data,error}=await supabase.from('evidence_records').select('evidence_id,title,evidence_type,verification_status,valid_until,related_request_id,related_product_id,related_product_version_id,sha256').eq('related_product_version_id',productVersionId).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function linkDocumentEvidence(documentId:string,evidenceId:string,supportArea:SupportArea){const {data,error}=await supabase.rpc('link_document_evidence',{target_document_id:documentId,target_evidence_id:evidenceId,target_support_area:supportArea});if(error)throw error;return data}
export async function unlinkDocumentEvidence(documentId:string,evidenceId:string){const {error}=await supabase.rpc('unlink_document_evidence',{target_document_id:documentId,target_evidence_id:evidenceId});if(error)throw error}
export async function approveDocument(documentId:string){const {data,error}=await supabase.rpc('approve_document',{target_document_id:documentId});if(error)throw error;return data}
export async function issueDocument(documentId:string){const {data,error}=await supabase.rpc('issue_document',{target_document_id:documentId});if(error)throw error;return data}
