import {supabase} from './supabase'

export async function listPackages(){const {data,error}=await supabase.from('documentation_packages').select('package_id,package_number,owner_organization_id,request_id,product_id,product_version_id,package_language,status,created_at,issued_at,superseded_at').order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function listPackageRequestOptions(){const {data,error}=await supabase.from('documentation_requests').select('request_id,request_number,request_status,product_description,preferred_document_language').eq('request_status','approved').order('updated_at',{ascending:false});if(error)throw error;return data||[]}
export async function createPackageDraft(requestId:string,language:'cs'|'en'){const {data,error}=await supabase.rpc('create_documentation_package_draft',{target_request_id:requestId,target_language:language});if(error)throw error;return data}
export async function issuePackage(packageId:string){const {data,error}=await supabase.rpc('issue_documentation_package',{target_package_id:packageId});if(error)throw error;return data}
export async function renderPackageArtifact(packageId:string){const {data,error}=await supabase.functions.invoke('render-issued-artifact',{body:{kind:'package',id:packageId}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
export async function renderDocumentArtifact(documentId:string){const {data,error}=await supabase.functions.invoke('render-issued-artifact',{body:{kind:'document',id:documentId}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
export async function listIssuedArtifacts(){const {data,error}=await supabase.from('issued_artifacts').select('artifact_id,request_id,document_id,package_id,artifact_kind,mime_type,sha256,file_size_bytes,template_version,source_snapshot_hash,artifact_language,created_at').order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function getArtifactUrl(artifactId:string){const {data,error}=await supabase.functions.invoke('get-issued-artifact-url',{body:{artifact_id:artifactId}});if(error)throw error;if(data?.error)throw new Error(data.error);return data as {url:string;expires_in:number;sha256:string;mime_type:string;artifact_kind:string;language:string}}
