import {FormEvent,useEffect,useState} from 'react'
import {FileCheck2,Plus} from 'lucide-react'
import {Link,useNavigate} from 'react-router-dom'
import {createDocumentDraft,listDocumentRequestOptions,listDocuments,type DocumentType} from '../lib/documents'
import {useAuth} from '../state/AuthContext'
const pretty=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
export function DocumentsPage(){const {membership}=useAuth();const nav=useNavigate();const [docs,setDocs]=useState<any[]>([]);const [requests,setRequests]=useState<any[]>([]);const [requestId,setRequestId]=useState('');const [type,setType]=useState<DocumentType>('technical_data_product_specification');const [language,setLanguage]=useState<'cs'|'en'>('en');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const polypak=membership?.member_role!=='customer_user'
 useEffect(()=>{(async()=>{try{const [d,r]=await Promise.all([listDocuments(),polypak?listDocumentRequestOptions():Promise.resolve([])]);setDocs(d);setRequests(r)}catch(e){setError(e instanceof Error?e.message:'Documents could not be loaded.')}})()},[polypak])
 const selected=requests.find(r=>r.request_id===requestId);const allowedTypes=(selected?.documentation_requested||[]) as DocumentType[]
 useEffect(()=>{if(selected?.preferred_document_language)setLanguage(selected.preferred_document_language)},[requestId])
 async function create(e:FormEvent){e.preventDefault();if(!requestId||!allowedTypes.includes(type)){setError('Select a document type requested for this Request.');return}setBusy(true);setError('');try{const d=await createDocumentDraft(requestId,type,language);nav(`/documents/${d.document_id}`)}catch(e){setError(e instanceof Error?e.message:'Document draft could not be created.')}finally{setBusy(false)}}
 return <><div className="page-heading"><div><div className="eyebrow">CONTROLLED OUTPUT</div><h1>Documents</h1><p>Draft, approve and issue controlled customer documentation from approved Requests and approved Product Versions.</p></div></div>{polypak&&<form className="panel form-section" onSubmit={create}><div><Plus/><h2>Create document draft</h2><p className="muted">Regulatory context and Product Version are assigned by the server.</p></div><div className="form-grid"><label className="field wide"><span>Approved Request *</span><select value={requestId} onChange={e=>{setRequestId(e.target.value);const r=requests.find(x=>x.request_id===e.target.value);const first=r?.documentation_requested?.[0] as DocumentType|undefined;if(first)setType(first)}}><option value="">Select Request</option>{requests.map(r=><option key={r.request_id} value={r.request_id}>{r.request_number} · {r.product_description}</option>)}</select></label><label className="field"><span>Document type *</span><select value={type} disabled={!requestId} onChange={e=>setType(e.target.value as DocumentType)}>{allowedTypes.length?allowedTypes.map(x=><option key={x} value={x}>{pretty(x)}</option>):<option value={type}>Select Request first</option>}</select></label><label className="field"><span>Language</span><select value={language} onChange={e=>setLanguage(e.target.value as 'cs'|'en')}><option value="en">English</option><option value="cs">Czech</option></select></label><div className="wide"><button className="primary" disabled={busy||!requestId}><FileCheck2 size={17}/>{busy?'Creating…':'Create controlled draft'}</button></div></div></form>}{error&&<div className="form-message">{error}</div>}<div className="table-panel"><div className="request-table"><div className="tr th"><span>Document</span><span>Customer</span><span>Status</span><span>Version</span><span>Updated</span></div>{docs.map(d=><Link className="tr row-link" key={d.document_id} to={`/documents/${d.document_id}`}><span><b>{pretty(d.document_type)}</b><small>{d.document_language.toUpperCase()}</small></span><span>{d.customer_name_snapshot}<small>{d.customer_reference_snapshot||'—'}</small></span><span><span className={`status status-${d.status}`}>{pretty(d.status)}</span></span><span>v{d.version_no}</span><span>{new Date(d.updated_at).toLocaleDateString()}</span></Link>)}{!docs.length&&<div className="empty">No documents yet.</div>}</div></div></>}
