import {FormEvent,useEffect,useState} from 'react'
import {ShieldCheck,Upload} from 'lucide-react'
import {listEvidence,setEvidenceStatus,uploadEvidence,verifyEvidenceFile,type EvidenceType} from '../lib/evidence'
import {useAuth} from '../state/AuthContext'
const TYPES:EvidenceType[]=['supplier_tds','supplier_declaration','laboratory_report','migration_report','certificate','drawing_specification','customer_attachment','internal_record','other']
const pretty=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
export function EvidencePage(){const {profile,membership}=useAuth();const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [file,setFile]=useState<File|null>(null);const [type,setType]=useState<EvidenceType>('supplier_tds');const [title,setTitle]=useState('');const [issuer,setIssuer]=useState('');const [reference,setReference]=useState('');const [validUntil,setValidUntil]=useState('')
 const allowed=membership?.member_role!=='customer_user';const reload=async()=>{try{setRows(await listEvidence())}catch(e){setError(e instanceof Error?e.message:'Evidence could not be loaded.')}}
 useEffect(()=>{if(allowed)reload()},[allowed])
 if(!allowed)return <div className="error-card">Evidence workspace is available only to authorized Polypak users.</div>
 async function upload(e:FormEvent){e.preventDefault();if(!file||!title.trim()||!profile)return;setBusy(true);setError('');try{await uploadEvidence({file,creatorProfileId:profile.profile_id,evidenceType:type,title,issuer,referenceNumber:reference,validUntil});setFile(null);setTitle('');setIssuer('');setReference('');setValidUntil('');await reload()}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy(false)}}
 async function action(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();await reload()}catch(e){setError(e instanceof Error?e.message:'Action failed.')}finally{setBusy(false)}}
 return <><div className="page-heading"><div><div className="eyebrow">EVIDENCE CONTROL</div><h1>Evidence</h1><p>Private source documents used to support Polypak documentation. Verification hashes are computed only by the trusted server flow.</p></div></div><form className="panel form-section" onSubmit={upload}><div><Upload/><h2>Upload evidence</h2><p className="muted">New evidence always enters the workflow as Unreviewed.</p></div><div className="form-grid"><label className="field"><span>File *</span><input type="file" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="field"><span>Evidence type *</span><select value={type} onChange={e=>setType(e.target.value as EvidenceType)}>{TYPES.map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></label><label className="field"><span>Title *</span><input value={title} required onChange={e=>setTitle(e.target.value)}/></label><label className="field"><span>Issuer</span><input value={issuer} onChange={e=>setIssuer(e.target.value)}/></label><label className="field"><span>Reference number</span><input value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="field"><span>Valid until</span><input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><div className="wide"><button className="primary" disabled={busy||!file||!title.trim()}>Upload as unreviewed</button></div></div></form>{error&&<div className="form-message evidence-message">{error}</div>}<div className="table-panel"><div className="request-table evidence-table"><div className="tr th"><span>Evidence</span><span>Scope</span><span>Status</span><span>Validity</span><span>Actions</span></div>{rows.map(r=><div className="tr" key={r.evidence_id}><span><b>{r.title}</b><small>{pretty(r.evidence_type)}{r.issuer?` · ${r.issuer}`:''}</small></span><span><small>{r.related_product_version_id?'Product version':r.related_product_id?'Product':r.related_request_id?'Request':'Unscoped'}</small></span><span><span className={`status status-${r.verification_status}`}>{pretty(r.verification_status)}</span>{r.sha256&&<small title={r.sha256}>SHA-256 {r.sha256.slice(0,10)}…</small>}</span><span>{r.valid_until||'—'}</span><span className="row-actions">{r.verification_status!=='verified'&&<><button className="small-action verify" disabled={busy} onClick={()=>action(()=>verifyEvidenceFile(r.evidence_id))}><ShieldCheck size={15}/>Verify file</button><button className="small-action" disabled={busy} onClick={()=>action(()=>setEvidenceStatus(r.evidence_id,'rejected'))}>Reject</button>{r.valid_until&&<button className="small-action" disabled={busy} onClick={()=>action(()=>setEvidenceStatus(r.evidence_id,'expired'))}>Expire</button>}</>}</span></div>)}</div></div></>}
