import {useEffect,useState} from 'react'
import {Download,PackageCheck,Plus} from 'lucide-react'
import {useAuth} from '../state/AuthContext'
import {createPackageDraft,getArtifactUrl,issuePackage,listIssuedArtifacts,listPackageRequestOptions,listPackages,renderPackageArtifact} from '../lib/packages'
const pretty=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
export function PackagesPage(){const {membership}=useAuth();const polypak=membership?.member_role!=='customer_user';const approver=['polypak_approver','polypak_admin'].includes(membership?.member_role||'');const [packages,setPackages]=useState<any[]>([]);const [requests,setRequests]=useState<any[]>([]);const [artifacts,setArtifacts]=useState<any[]>([]);const [requestId,setRequestId]=useState('');const [language,setLanguage]=useState<'cs'|'en'>('en');const [busy,setBusy]=useState(false);const [error,setError]=useState('')
 const reload=async()=>{try{const [p,a]=await Promise.all([listPackages(),listIssuedArtifacts()]);setPackages(p);setArtifacts(a);if(polypak)setRequests(await listPackageRequestOptions())}catch(e){setError(e instanceof Error?e.message:'Could not load packages.')}}
 useEffect(()=>{reload()},[polypak])
 async function run(fn:()=>Promise<any>){setBusy(true);setError('');try{await fn();await reload()}catch(e){setError(e instanceof Error?e.message:'Action failed.')}finally{setBusy(false)}}
 async function download(id:string){setBusy(true);setError('');try{const a=await getArtifactUrl(id);window.open(a.url,'_blank','noopener,noreferrer')}catch(e){setError(e instanceof Error?e.message:'Download link could not be created.')}finally{setBusy(false)}}
 const controls=(p:any)=>{const artifact=artifacts.find(a=>a.package_id===p.package_id&&a.artifact_kind==='package_pdf');return <div className="row-actions">{p.status==='draft'&&approver&&<button className="small-action verify" disabled={busy} onClick={()=>run(()=>issuePackage(p.package_id))}><PackageCheck size={15}/>Issue</button>}{p.status==='issued'&&polypak&&!artifact&&<button className="small-action" disabled={busy} onClick={()=>run(()=>renderPackageArtifact(p.package_id))}>Generate PDF</button>}{artifact&&<button className="small-action verify" disabled={busy} onClick={()=>download(artifact.artifact_id)}><Download size={15}/>PDF</button>}</div>}
 return <><div className="page-heading"><div><div className="eyebrow">ISSUED DOCUMENTATION</div><h1>Documentation Packages</h1><p>Immutable issued documentation and secure PDF access.</p></div></div>{polypak&&<div className="panel form-section"><div><Plus/><h2>Create package draft</h2><p className="muted">The server selects the issued Document 1 and Document 2 with matching request, product version and language.</p></div><div className="form-grid"><label className="field wide"><span>Approved request</span><select value={requestId} onChange={e=>{setRequestId(e.target.value);const r=requests.find(x=>x.request_id===e.target.value);if(r?.preferred_document_language)setLanguage(r.preferred_document_language)}}><option value="">Select request</option>{requests.map(r=><option key={r.request_id} value={r.request_id}>{r.request_number||r.request_id.slice(0,8)} · {r.product_description}</option>)}</select></label><label className="field"><span>Package language</span><select value={language} onChange={e=>setLanguage(e.target.value as 'cs'|'en')}><option value="en">English</option><option value="cs">Čeština</option></select></label><div className="wide"><button className="primary" disabled={busy||!requestId} onClick={()=>run(()=>createPackageDraft(requestId,language))}>Create controlled draft</button></div></div></div>}{error&&<div className="form-message evidence-message">{error}</div>}<div className="table-panel"><div className="request-table desktop-table"><div className="tr th"><span>Package</span><span>Language</span><span>Status</span><span>Issued</span><span>Actions</span></div>{packages.map(p=><div className="tr" key={p.package_id}><span><b>{p.package_number||'Draft package'}</b><small>{p.package_id.slice(0,8)}</small></span><span>{p.package_language.toUpperCase()}</span><span><span className={`status status-${p.status}`}>{pretty(p.status)}</span></span><span>{p.issued_at?new Date(p.issued_at).toLocaleDateString():'—'}</span><span>{controls(p)}</span></div>)}</div><div className="mobile-request-list">{packages.map(p=><article className="request-card" key={p.package_id}><div><b>{p.package_number||'Draft package'}</b><span className={`status status-${p.status}`}>{pretty(p.status)}</span></div><h3>{p.package_language.toUpperCase()} documentation package</h3><p>{p.issued_at?`Issued ${new Date(p.issued_at).toLocaleDateString()}`:'Not issued yet'}</p>{controls(p)}</article>)}</div></div><div className="panel artifact-panel"><div><h2>Issued files</h2><p className="muted">Download links are generated on demand and expire after 5 minutes.</p></div><div className="artifact-list">{artifacts.map(a=><div className="artifact-row" key={a.artifact_id}><div><b>{pretty(a.artifact_kind)}</b><small>{a.artifact_language?.toUpperCase()} · {a.template_version} · SHA-256 {a.sha256.slice(0,12)}…</small></div><button className="small-action verify" disabled={busy} onClick={()=>download(a.artifact_id)}><Download size={15}/>Open PDF</button></div>)}</div></div></>}
