import {useEffect,useState} from 'react'
import {Link,useParams} from 'react-router-dom'
import {Plus} from 'lucide-react'
import {approveProductVersion,getVersions} from '../lib/products'
import {supabase} from '../lib/supabase'
import {useAuth} from '../state/AuthContext'

type Version={product_version_id:string;version_no:number;product_name:string;product_type:string;primary_material:string;material_code:string;printed:boolean;approved_at:string|null}
export function ProductDetailPage(){const {productId}=useParams();const {membership}=useAuth();const [product,setProduct]=useState<any>(null);const [versions,setVersions]=useState<Version[]>([]);const [error,setError]=useState('');const approver=['polypak_approver','polypak_admin'].includes(membership?.member_role||'');async function load(){if(!productId)return;const {data,error}=await supabase.from('products').select('product_id,sku_code,product_name,product_type,status,current_version_no').eq('product_id',productId).single();if(error){setError(error.message);return}setProduct(data);try{setVersions(await getVersions(productId) as Version[])}catch(e){setError(e instanceof Error?e.message:'Versions unavailable.')}}useEffect(()=>{load()},[productId]);async function approve(id:string){setError('');try{await approveProductVersion(id);await load()}catch(e){setError(e instanceof Error?e.message:'Approval failed.')}}if(membership?.member_role==='customer_user')return <div className="error-card">Polypak access required.</div>;if(!product)return <div className="empty">{error||'Loading product…'}</div>;const next=Math.max(0,...versions.map(v=>v.version_no))+1;return <><div className="page-heading"><div><div className="eyebrow">{product.sku_code}</div><h1>{product.product_name}</h1><p>{product.product_type} · {product.status}</p></div><Link className="primary button-link" to={`/products/${productId}/versions/new?version=${next}`}><Plus size={17}/>New version</Link></div>{error&&<div className="form-message">{error}</div>}<div className="table-panel"><div className="request-table desktop-table"><div className="tr th"><span>Version</span><span>Specification</span><span>Material</span><span>Printing</span><span>Status</span></div>{versions.map(v=><div className="tr" key={v.product_version_id}><span><b>v{v.version_no}</b></span><span>{v.product_name}<small>{v.product_type}</small></span><span>{v.primary_material}<small>{v.material_code}</small></span><span>{v.printed?'Printed':'Unprinted'}</span><span>{v.approved_at?<span className="status status-approved">Approved</span>:approver?<button className="secondary" onClick={()=>approve(v.product_version_id)}>Approve</button>:<span className="status">Draft</span>}</span></div>)}</div><div className="mobile-request-list">{versions.map(v=><article className="request-card" key={v.product_version_id}><div><b>Version {v.version_no}</b>{v.approved_at?<span className="status status-approved">Approved</span>:<span className="status">Draft</span>}</div><h3>{v.product_name}</h3><p>{v.primary_material} · {v.printed?'Printed':'Unprinted'}</p>{!v.approved_at&&approver&&<button className="secondary" onClick={()=>approve(v.product_version_id)}>Approve version</button>}</article>)}</div></div></>}
