import { useEffect,useMemo,useState } from 'react'
import { Plus,Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import type { DocumentationRequest,RequestStatus } from '../lib/contracts'
import { REQUEST_STATUSES } from '../lib/contracts'

export function RequestsPage(){const [rows,setRows]=useState<DocumentationRequest[]>([]);const [loading,setLoading]=useState(true);const [query,setQuery]=useState('');const [status,setStatus]=useState<RequestStatus|''>('')
 useEffect(()=>{(async()=>{setLoading(true);const {data,error}=await supabase.from('documentation_requests').select('request_id,owner_organization_id,request_number,request_status,customer_reference,product_description,intended_use,customer_role,market_scope,preferred_document_language,linked_product_id,submitted_at,updated_at').order('updated_at',{ascending:false});if(!error)setRows((data||[]) as DocumentationRequest[]);setLoading(false)})()},[])
 const filtered=useMemo(()=>rows.filter(r=>(!status||r.request_status===status)&&(!query||`${r.request_number||''} ${r.customer_reference||''} ${r.product_description}`.toLowerCase().includes(query.toLowerCase()))),[rows,query,status])
 return <><div className="page-heading"><div><div className="eyebrow">WORKSPACE</div><h1>Documentation Requests</h1><p>Requests visible to your account according to production access rules.</p></div><Link className="primary button-link" to="/requests/new"><Plus size={17}/>New request</Link></div><div className="toolbar"><label className="search"><Search size={17}/><input placeholder="Search request, reference or product" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={status} onChange={e=>setStatus(e.target.value as RequestStatus|'')}><option value="">All statuses</option>{REQUEST_STATUSES.map(s=><option key={s} value={s}>{pretty(s)}</option>)}</select></div><div className="table-panel">{loading?<div className="empty">Loading requests…</div>:filtered.length===0?<div className="empty">No matching requests.</div>:<><div className="request-table desktop-table"><div className="tr th"><span>Request</span><span>Product</span><span>Role / market</span><span>Status</span><span>Updated</span></div>{filtered.map(r=><Link className="tr request-row-link" to={`/requests/${r.request_id}`} key={r.request_id}><span><b>{r.request_number||'Pending number'}</b><small>{r.customer_reference||'No customer reference'}</small></span><span>{r.product_description}</span><span>{pretty(r.customer_role)}<small>{pretty(r.market_scope)}</small></span><span><Status value={r.request_status}/></span><span>{new Date(r.updated_at).toLocaleDateString()}</span></Link>)}</div><div className="mobile-request-list">{filtered.map(r=><Link className="request-card request-row-link" to={`/requests/${r.request_id}`} key={r.request_id}><div><b>{r.request_number||'Pending number'}</b><Status value={r.request_status}/></div><h3>{r.product_description}</h3><p>{pretty(r.customer_role)} · {pretty(r.market_scope)}</p><small>Updated {new Date(r.updated_at).toLocaleDateString()}</small></Link>)}</div></>}</div></>}
function pretty(s:string){return s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function Status({value}:{value:RequestStatus}){return <span className={`status status-${value}`}>{pretty(value)}</span>}
